lib/tphx_web/router.ex
defmodule TphxWeb.Router do
  use TphxWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TphxWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/products", ProductController
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete]

    #get "/products", ProductsController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", TphxWeb do
  #   pipe_through :api
  # end
end

lib/tphx_web/views/layout_view.ex
defmodule TphxWeb.LayoutView do
  use TphxWeb, :view

  def current_user(conn) do
    Plug.Conn.get_session(conn, :current_user)
  end

end

lib/tphx_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <title>Tphx · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>   
          <div>      
            <ul class="nav">
              <li class="nav-item">                
                <span class="nav-link"><%= link "Home", to: Routes.page_path(@conn, :index) %></span>
              </li>
              <li class="nav-item">              
                <span class="nav-link">  <%= link "Products", to: Routes.product_path(@conn, :index) %> </span>
              </li>
              <li class="nav-item">                
                <span class="nav-link">  <%= link "Users", to: Routes.user_path(@conn, :index) %> </span>
              </li>              
            </ul>
          </div>
      <section class="container">
        <nav role="navigation">
          <div>
            <ul><!--            <li><a href="https://hexdocs.pm/phoenix/overview.html">Get Started</a></li> -->
              <li>
                  <%= if user = current_user(@conn) do %>
                    Logged in as
                    <strong><%= user.username %></strong>
                    <br>
                    <%= link "Log out", to: Routes.session_path(@conn, :delete, user.id), method: :delete %>
                  <% else %>
                    <%= link "Log in", to: Routes.session_path(@conn, :new) %>
                  <% end %>
              </li>
            </ul>
          </div>  
        </nav>
        <a href="http://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>